export const studies_pl = [
	'akademiki',
	'stołówka',
	'teren uczelni',
	'biblioteka',
	'rdzewiak',
	'czesne',
	'rektor',
	'wykłady',
	'dziekan',
	'aula/ sala wykładowa',
	'laboratoria',
	'wydział',
	'wydział budownictwa',
	'inżynieria środowiska',
	'kierunek studiów',
	'profesor',
	'wykładowca',
	'Doktor',
	'sprawozdanie',
	'praca domowa',
	'egzamin',
	'test',
	'słuchanie',
	'uczenie się, nauka',
	'wykłady',
	'wychowanie fizyczne',
	'stopień',
	'ukończyć',
	'licencjat',
	'Inżynier',
	'magister nauk humanistycznych',
	'magister nauk ścisłych',
	'specjalizować się w czymś',
	'laboratoria',
	'podejść do egzaminu',
	'zdać egzamin',
	'nie zdać egzaminu',
	'pisać poprawkę z egzaminu',
	'rzucić studia',
	'zostać wyrzuconym ze studiów',
	'projekt',
	'prezentować coś',
	'wkuwać',
	'dostać stypendium',
	'dokładny,precyzyjny',
	'dokładny',
	'promotor',
	'seminarium',
	'absolutorium, świadectwo ukończenia',
	'obrona pracy magisterskiej',
	'obrona pracy doktorskiej',
	'uzyskać zaliczenie',
	'komisja egzaminacyjna',
	'stypendium socjalne',
	'asystent',
	'praktykant',
	'wiedza specjalistyczna',
	'nauki ścisłe',
	'wykształcenie',
	'znajomość tematyki',
	'w dziedzinie',
	'nauki humanistyczne',
]

export const studies_eng = [
	'dormitories,hall of residence',
	'canteen',
	'campus',
	'library',
	'the rusty building',
	'tuition',
	'rector',
	'lectures',
	'dean',
	'lecture hall',
	'laboratories',
	'faculty',
	'Civil engineering',
	'Enviromental engineering',
	'field of study',
	'professor',
	'lecturer',
	'PhD',
	'report',
	'assigment',
	'exam',
	'test',
	'listening',
	'learning',
	'lectures',
	'PE',
	'degree',
	'to graduate from',
	'BSc (Bachelor of Science)',
	'BA (Bachelor of Arts)',
	'MSc (Master of Science)',
	'MA (Master of arts)',
	'to major in sth',
	'lab classes',
	'to take an exam',
	'to pass an exam',
	'to fail an exam',
	'to retake an exam',
	'to drop out',
	'to be expelled from',
	'projects',
	'to give a presentation',
	'to cram',
	'get scholarship',
	'precise',
	'accurate',
	'thesis supervisor',
	'a seminar',
	'certificate of completion',
	"a defence of master's thesis",
	'a defence of doctoral thesis',
	'to get a credit',
	'an exam board',
	'a maintenance prest',
	'TA',
	'a trainee',
	'expertise',
	'the exact science',
	'educational background',
	'know how',
	'in the field of',
	'the humanities',
]

export const gps_pl = [
	'geodeta',
	'geodezja i kartografia',
	"przycisk 'człowiek za burtą'",
	"badanie topograficzne 'geodezja'",
	'zastosowanie w',
	'zastosowanie morskie',
	'zapewnić',
	'umożliwić',
	'umożlić, pozwolić',
	'pozwolić',
	'uniemożliwić',
	'długość geograficzna',
	'wysokość geograficzna',
	'szerokość geograficzna',
	'wznosić, podnosić (coś przez kogoś)',
	'samo się wznosi, przyrost, wzrost (podwyżka)',
	'wznosić',
	'opadać',
	'równik',
	'morski (określenie czegoś morskiego)',
]

export const gps_eng = [
	'surveyor',
	'surveying and mapping',
	'man overboard',
	'topographical surveying',
	'applications in',
	'maritime applications',
	'ensure, make sure',
	'enable',
	'allows',
	'permits',
	'prevent',
	'longitude',
	'altitude',
	'latitude',
	'raise',
	'rise',
	'ascend',
	'descend',
	'equator',
	'maritime',
]

export const sp_el_pl = [
	'wystrzelić',
	'zrównoważony',
	'ładunek',
	'zmniejszyć',
	'złożony',
	'wdrożyć',
	'wytrzymałość na rozciąganie',
	'zawieszony',
	'utrzymać',
	'zutylizować',
	'napięty, naprężony',
	'obrócić',
	'wzmocniony',
	'kamień milowy (kroki kontrolne w projekcie)',
	'wiarygodny',
	'bezzałogowy',
	'odpady kosmiczne',
	'pilnie',
	'napęd',
]

export const sp_el_eng = [
	'to launch',
	'sustainable',
	'cargo',
	'to decrease',
	'complex',
	'to implement',
	'tensile strength',
	'suspended',
	'to maintain',
	'to utilize',
	'taut',
	'to rotate',
	'fortified',
	'milestone',
	'plausible',
	'unmanned',
	'space debris',
	'urgently',
	'propulsion',
]

export const otis_el_pl = [
	'ulepszyć',
	'wyeliminować, zredukować coś do zera',
	'coś lepsze od czegoś',
	'zredukować',
	'wydajny',
	'szyb windy',
	'uszczelnione łożysko',
	'smarować',
	'smarowanie',
	'bezprzekładniowy',
	'trwałość',
	'niezawodność',
	'wykryć usterki',
	'konserwacja',
	'poinformować kogoś',
	'przeprowadzić',
	'znacząco',
	'zużycie',
	'położyć nacisk, podkreślić',
	'całkowicie',
	'znacząco',
	'znacząco',
]

export const otis_el_eng = [
	'enhance',
	'eliminate',
	'superior',
	'reduce',
	'efficient',
	'hoistway',
	'sealed bearing',
	'lubricate',
	'lubrication',
	'gearless',
	'durability',
	'reliability',
	'to detect faults',
	'maintenance',
	'to brief somebody',
	'to conduct',
	'significantly',
	'wear and tear',
	'emphasise',
	'totally/ entirely/ completely',
	'considerably',
	'highly',
]
